In [1]:
import sys
import os
import warnings
import time
import inspect
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# Addthe parent directory to the system path to access the 'src' module.
# Assuming this notebook resides in 'notebooks/', '..' resolves to the project root.
sys.path.append(os.path.abspath('..'))

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.width', 500)

train_path = "../data/train.csv"
test_path = "../data/test.csv"

def load_data(path):
    data = pd.read_csv(path)
    return data

df = load_data(train_path)
df.head()

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

In [2]:
test_df = load_data(test_path)
test_df.head()

   PassengerId  Pclass                                          Name     Sex    Age  SibSp  Parch   Ticket   Fare Cabin Embarked
0          892       3                              Kelly, Mr. James    male 34.500      0      0   330911  7.829   NaN        Q
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female 47.000      1      0   363272  7.000   NaN        S
2          894       2                     Myles, Mr. Thomas Francis    male 62.000      0      0   240276  9.688   NaN        Q
3          895       3                              Wirz, Mr. Albert    male 27.000      0      0   315154  8.662   NaN        S
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female 22.000      1      1  3101298 12.287   NaN        S

In [3]:
def check_df(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    print("##################### Info #####################")
    print(dataframe.info())
    print("##################### Types #####################")
    display(dataframe.dtypes.to_frame("Type"))
    print("##################### Head #####################")
    display(dataframe.head(head))
    print("##################### Tail #####################")
    display(dataframe.tail(head))
    print("##################### Describe #####################")
    display(dataframe.describe([0, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99, 1]).T)
    print("\n###################### Unique Value Counts per Column ######################")
    display(dataframe[dataframe.columns].nunique())
    print("##################### NA #####################")
    display(dataframe.isnull().sum().to_frame("Missing Values"))

check_df(df)

##################### Shape #####################
(891, 12)
##################### Info #####################
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
##################### Types #####################

                Type
PassengerId    int64
Survived       int64
Pclass         int64
Name          object
Sex           object
Age          float64
SibSp          int64
Parch          int64
Ticket        object
Fare         float64
Cabin         object
Embarked      object

##################### Head #####################

   PassengerId  Survived  Pclass                                               Name     Sex    Age  SibSp  Parch            Ticket   Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male 22.000      1      0         A/5 21171  7.250   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female 38.000      1      0          PC 17599 71.283   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female 26.000      0      0  STON/O2. 3101282  7.925   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female 35.000      1      0            113803 53.100  C123        S
4            5         0       3                           Allen, Mr. William Henry    male 35.000      0      0            373450  8.050   NaN        S

##################### Tail #####################

     PassengerId  Survived  Pclass                                      Name     Sex    Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886          887         0       2                     Montvila, Rev. Juozas    male 27.000      0      0      211536 13.000   NaN        S
887          888         1       1              Graham, Miss. Margaret Edith  female 19.000      0      0      112053 30.000   B42        S
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"  female    NaN      1      2  W./C. 6607 23.450   NaN        S
889          890         1       1                     Behr, Mr. Karl Howell    male 26.000      0      0      111369 30.000  C148        C
890          891         0       3                       Dooley, Mr. Patrick    male 32.000      0      0      370376  7.750   NaN        Q

##################### Describe #####################

              count    mean     std   min    0%     5%     25%     50%     75%     95%     99%    100%     max
PassengerId 891.000 446.000 257.354 1.000 1.000 45.500 223.500 446.000 668.500 846.500 882.100 891.000 891.000
Survived    891.000   0.384   0.487 0.000 0.000  0.000   0.000   0.000   1.000   1.000   1.000   1.000   1.000
Pclass      891.000   2.309   0.836 1.000 1.000  1.000   2.000   3.000   3.000   3.000   3.000   3.000   3.000
Age         714.000  29.699  14.526 0.420 0.420  4.000  20.125  28.000  38.000  56.000  65.870  80.000  80.000
SibSp       891.000   0.523   1.103 0.000 0.000  0.000   0.000   0.000   1.000   3.000   5.000   8.000   8.000
Parch       891.000   0.382   0.806 0.000 0.000  0.000   0.000   0.000   0.000   2.000   4.000   6.000   6.000
Fare        891.000  32.204  49.693 0.000 0.000  7.225   7.910  14.454  31.000 112.079 249.006 512.329 512.329

###################### Unique Value Counts per Column ######################

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

##################### NA #####################

             Missing Values
PassengerId               0
Survived                  0
Pclass                    0
Name                      0
Sex                       0
Age                     177
SibSp                     0
Parch                     0
Ticket                    0
Fare                      0
Cabin                   687
Embarked                  2

In [5]:
def grab_col_names(dataframe, cat_th=10, car_th=20):
    """
    Returns the names of categorical, numerical, and categorical but cardinal columns in the dataset.
    
    Note: Categorical columns also include those that are numerically-coded but categorical in nature.
    
    Parameters
    ----------
        dataframe: pandas.DataFrame
                The dataframe from which the column names are to be extracted.
        cat_th: int, optional
                The threshold for the number of unique values to classify a numerical column as categorical.
        car_th: int, optional
                The threshold for the number of unique values to classify a categorical column as cardinal.
    
    Returns
    -------
        cat_cols: list
                A list of the names of categorical columns.
        num_cols: list
                A list of the names of numerical columns.
        cat_but_car: list
                A list of the names of categorical columns that are considered cardinal.
        num_but_cat: list
                A list of the names of numerical columns that are considered categorical.
    
    Examples
    --------
        import seaborn as sns
        df = sns.load_dataset("iris")
        print(grab_col_names(df))
    
    Notes
    -----
        - The sum of the lengths of cat_cols, num_cols, and cat_but_car equals the total number of columns.
        - Columns identified as "numeric but categorical" are included within the cat_cols list.
        - The total number of columns is equal to the sum of the lengths of the three returned lists: len(cat_cols) + len(num_cols) + len(cat_but_car).

    """

    # cat_cols, cat_but_car
    cat_cols = [col for col in dataframe.columns if dataframe[col].dtypes == "O"]
    num_but_cat = [col for col in dataframe.columns if dataframe[col].nunique() <= cat_th and dataframe[col].dtypes != "O"]
    cat_but_car = [col for col in dataframe.columns if dataframe[col].nunique() > car_th and dataframe[col].dtypes == "O"]

    cat_cols = cat_cols + num_but_cat
    cat_cols = [col for col in cat_cols if col not in cat_but_car]

    # num_cols
    num_cols = [col for col in dataframe.columns if dataframe[col].dtypes != "O"]
    num_cols = [col for col in num_cols if col not in num_but_cat]

    print(f"Observations: {dataframe.shape[0]}")
    print(f"Variables: {dataframe.shape[1]}")
    print(f"cat_cols: {len(cat_cols)}")
    print(f"num_cols: {len(num_cols)}")
    print(f"cat_but_car: {len(cat_but_car)}")
    print(f"num_but_cat: {len(num_but_cat)}")

    return cat_cols, num_cols, cat_but_car, num_but_cat

cat_cols, num_cols, cat_but_car, num_but_cat = grab_col_names(df)

num_cols = [col for col in num_cols if col not in "Id"]

Observations: 891
Variables: 12
cat_cols: 6
num_cols: 3
cat_but_car: 3
num_but_cat: 4